### ISSUE TITLE
Don't use Job Names (Anemic Domain Model)

### ISSUE THREAD

**Issue by manuelkollus** [HytaleMarket/hytale-web-api-client-java#6]
There are those class names that one comes across in almost every ~~object oriented~~ codebase, some examples are:

- `UserManager`
- `JsonParser`
- `RequestHandler`

A lot of these classes have one single exported method like:
- `parseJson`
- `handleRequest`

Whilst others have so many responsibilities, that their name becomes very generic 
like `Manager` or `Service`. But they have something in common, they consist of procedures,
operating on data, rather than objects exposing behaviour. And some just have a badly chosen name.

The real problem is not their name but their design. In order to avoid such classes,
move stop exposing data, move methods closer to the data they operate on and start

**Comment by Krymonota** [comment]
Don't get me wrong - I basically agree. 

But in this case it would be very exaggerated to introduce a breaking change only because of the name of a single class (`HytaleWebApiManager`). From my point of view and that of the Retrofit developers and community, `HytaleWebApiService` is an excellent class name, but it seems like some can argue about it. I'm pretty sure a large majority of the developers using this project don't care about this "issue" because of the simplicity of this project. I'm not willing to spend my time on overengineering when there's virtually no added value and compatibility is lost due to unnecessary breaking changes (just in this case, not in general).

Thanks though.
